from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional
import database as db
import uuid

app = FastAPI(title="DataTrace API", version="1.0")

# --- Pydantic 模型 (用于请求体验证) ---
class DatasetCreate(BaseModel):
    name: str
    description: str
    tags: List[str]

class RecordCreate(BaseModel):
    input_ids: List[str]
    operation: str
    description: str
    output_suffix: str = "_processed"

# --- API 路由 ---

@app.get("/")
def health_check():
    return {"status": "running", "system": "DataTrace Pro"}

# api_server.py 修改部分

@app.post("/datasets/")
def create_dataset(item: DatasetCreate):
    # 1. 先检查是否已存在同名数据集
    existing = db.search_datasets(query=item.name)
    # 精确匹配名称
    target = next((d for d in existing if d['name'] == item.name), None)
    
    if target:
        # 如果存在，直接返回旧的 ID，不报错 (Idempotency)
        return {
            "id": target['id'], 
            "name": target['name'], 
            "message": "Dataset already exists, returning existing ID.",
            "new": False
        }

    # 2. 不存在则创建
    ds_id = str(uuid.uuid4())[:8]
    db.add_dataset(ds_id, item.name, item.description, item.tags)
    return {
        "id": ds_id, 
        "name": item.name, 
        "message": "Dataset registered successfully",
        "new": True
    }

@app.get("/datasets/search")
def search_datasets(q: Optional[str] = None, tags: Optional[str] = None):
    # tags 传入逗号分隔字符串
    tag_list = tags.split(",") if tags else []
    results = db.search_datasets(query=q, tags=tag_list)
    return {"count": len(results), "results": results}

@app.post("/transform/")
def create_transformation(item: RecordCreate):
    # 1. 验证输入数据集是否存在
    inputs = []
    for i_id in item.input_ids:
        ds = db.get_dataset_by_id(i_id)
        if not ds:
            raise HTTPException(status_code=404, detail=f"Input dataset {i_id} not found")
        inputs.append(ds)
    
    # 2. 生成新数据集名称
    input_names = [d['name'] for d in inputs]
    if len(input_names) > 1:
        base_name = "merged_dataset"
    else:
        base_name = input_names[0]
    
    new_name = f"{base_name}_{item.operation.lower()}"
    new_id = str(uuid.uuid4())[:8]
    
    # 3. 继承标签
    all_tags = set()
    for d in inputs:
        if d['tags']: all_tags.update(d['tags'].split(","))
    all_tags.add(item.operation.lower())
    all_tags.add("generated")
    
    # 4. 写入数据库
    new_desc = f"Generated by {item.operation} from {', '.join(input_names)}. {item.description}"
    db.add_dataset(new_id, new_name, new_desc, list(all_tags))
    rec_id = str(uuid.uuid4())[:8]
    db.add_record(rec_id, item.input_ids, item.operation, item.description, [new_id])
    
    return {
        "record_id": rec_id,
        "output_dataset": {"id": new_id, "name": new_name}
    }

# 启动方式：uvicorn api_server:app --reload
